language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8


install:
  - export CXX="g++-4.8"
  - g++ --version


script:
  - g++ src/* -I./include -o UDrive


