sudo: false
language: python
compiler: gcc
python: 
  - "2.7"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libgtest-dev


before_install:
  - pip install --upgrade pip

install:
  - export CXX="g++-4.9"
  - g++ --version
  - pip install requests

before_script:
  - chmod +x travis/*
  - chmod +x build.sh
  - HOME=`pwd`
  - mkdir lib
  - export LIB="$HOME/lib"
  - export INCLUDE="$HOME/include"

  # Compilar GTest
  - ./travis/compilarGTest.sh
  - GTEST="$HOME/googletest-master/googletest"
  - cp $GTEST/build/lib*.a $LIB/
  - cp -r $GTEST/include/gtest $INCLUDE/ 

  - cd $HOME

  # Para debug
  - find . -type d
  - ls $LIB
  - ls $INCLUDE/gtest/

  - mkdir build
  - cp "default.jpg" "build"
  - cd build
  - mkdir files

script:
  - cmake -Dtest=ON -Drocksdb=OFF ../ && make unitTest && ./unitTest && make udrive && python ../test/server_test.py -v && python ../test/version_test.py -v

after_failure:
  - echo LOG; cat files/log.txt
