sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libgtest-dev

install:
  - export CXX="g++-4.8"
  - g++ --version

before_script:
  - chmod +x travis/*
  - HOME=`pwd`
  - mkdir lib
  - export LIB="$HOME/lib"
  - export INCLUDE="$HOME/include"

  # Compilar GTest
  - ./travis/compilarGTest.sh
  - GTEST="$HOME/googletest-master/googletest"
  - cp $GTEST/build/lib*.a $LIB/
  - cp -r $GTEST/include/gtest $INCLUDE/ 

  - cd $HOME
  
  # Para debug
  - find . -type d
  - ls $LIB
  - ls $INCLUDE/gtest/

  - mkdir build
  - cd build

script:
  - cmake -Dtest=ON -Drocksdb=OFF ../; make unitTest; ./unitTest 


# cache:
#   directories:
#     - rocksdb-master
#     - googletest-master
