language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8


install:
  - echo 'INSTALL'
  - export CXX="g++-4.8"
  - g++ --version


script:
  - echo 'SCRIPT'
  - g++ src/main.cpp -o holaMundo
  - ./holaMundo

